// components/solid/src/core/card.tsx
import { JSX, splitProps } from "solid-js";

interface CardProps extends JSX.HTMLAttributes<HTMLDivElement> {}

const Card = (props: CardProps) => 
    {
        const [local, rest] = splitProps(props, ['class'])

        return (
    <div
      class={
        "bg-base-0 border-base-300 text-base-800 rounded border shadow-sm " +
        local.class
      }
      {...rest}
    />
  )};

interface CardHeaderProps extends JSX.HTMLAttributes<HTMLDivElement> {}


const CardHeader = ( props : CardHeaderProps) => 
    
    {
        const [local, rest] = splitProps(props, ['class'])
    return    (
    <div
      class={"flex flex-col space-y-1.5 p-6 " + local.class}
      {...rest}
    />
  )}


interface CardTitleProps extends JSX.HTMLAttributes<HTMLDivElement> {}


const CardTitle = ( props: CardTitleProps) =>
    
    {
        const [local, rest] = splitProps(props, ['class'])

        return(
    <div
      
      class={
        "text-2xl font-semibold leading-none tracking-tight " + local.class
      }
      {...rest}
    />
  
)};

interface CardDescriptionProps extends JSX.HTMLAttributes<HTMLDivElement> {}


const CardDescription = (props: CardDescriptionProps) => 
    
    {
        const [local, rest] = splitProps(props, ['class'])

        return(
  <div class={"text-base-500 text-sm " + local.class} {...rest} />
)}

interface CardBodyProps extends JSX.HTMLAttributes<HTMLDivElement> {}

const CardBody = (props: CardBodyProps) => 
    
   {
    const [local, rest] = splitProps(props, ['class'])


   return (
  <div class={"p-6 pt-0 " + local.class} {...rest} />
)}


interface CardFooterProps extends JSX.HTMLAttributes<HTMLDivElement> {}

const CardFooter =  (props: CardFooterProps) => {
    const [local, rest] = splitProps(props, ['class'])

   return (
    <div
      class={"flex items-center gap-4 px-6 pb-6 " + local.class}
      {...rest}
    />
  )}


export { Card, CardBody, CardDescription, CardFooter, CardHeader, CardTitle };

// apps/web/src/react/components/core/card.tsx
import { forwardRef, HTMLAttributes } from "react";

const Card = forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={
        "rounded border border-neutral-300 bg-white text-neutral-800 shadow-sm " +
        className
      }
      {...props}
    />
  )
);
Card.displayName = "Card";

const CardHeader = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={"flex flex-col space-y-1.5 p-6 " + className}
      {...props}
    />
  )
);
CardHeader.displayName = "CardHeader";

const CardTitle = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={
        "text-2xl font-semibold leading-none tracking-tight " + className
      }
      {...props}
    />
  )
);
CardTitle.displayName = "CardTitle";

const CardDescription = forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={"text-sm text-neutral-500 " + className}
    {...props}
  />
));
CardDescription.displayName = "CardDescription";

const CardBody = forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div ref={ref} className={"p-6 pt-0 " + className} {...props} />
));
CardBody.displayName = "CardBody";

const CardFooter = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={"flex items-center px-6 pb-6 gap-4 " + className}
      {...props}
    />
  )
);
CardFooter.displayName = "CardFooter";

export { Card, CardHeader, CardFooter, CardTitle, CardDescription, CardBody };
