// components/solid/src/core/code.tsx
import { cva, VariantProps } from "class-variance-authority";
import { JSX, splitProps } from "solid-js";

 const codeStyle = cva(
  "border-base-300 bg-base-100 text-base-800 inline-flex items-center whitespace-pre rounded border font-medium",
  {
    variants: {
      size: {
        sm: "px-0.5 text-xs",
        md: "px-1 pb-px text-sm",
        lg: "px-1.5 pb-0.5 pt-px",
      },
    },
    defaultVariants: {
      size: "md",
    },
  },
);



 interface CodeProps
  extends JSX.HTMLAttributes<HTMLElement>,
    VariantProps<typeof codeStyle> {}

 const Code = (props: CodeProps) => {

    const [local, rest] = splitProps(props, [
        "size"
      ]);
      const {children} = rest
    return (
      
      <code
        style={{
          "font-family": "Courier New, Arial, Georgia ,Times New Roman, ubuntu",
        }}
        class={codeStyle({ size: local.size })}
        {...rest}
      >
        {children}
      </code>
    )
  };


export {Code}

// apps/web/src/react/components/core/code.tsx
import { cva, VariantProps } from "class-variance-authority";
import React, { forwardRef } from "react";

export const codeStyle = cva(
  "inline-flex items-center whitespace-pre rounded font-medium",
  {
    variants: {
      variant: {
        outline: "border border-neutral-300 bg-neutral-100",
        ghost: "bg-neutral-100",
      },
      size: {
        sm: "px-0.5 text-xs",
        md: "px-1 pb-px text-sm",
        lg: "px-1.5 pb-0.5 pt-px",
      },
    },
    defaultVariants: {
      size: "md",
      variant: "outline",
    },
  }
);

export interface CodeProps
  extends Omit<
      React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>,
      "size"
    >,
    VariantProps<typeof codeStyle> {}

export const Code = forwardRef<HTMLElement, CodeProps>(
  ({ size, variant, children, ...props }, ref) => {
    return (
      <code
        ref={ref}
        style={{
          fontFamily: "Courier New, Arial, Georgia ,Times New Roman, ubuntu",
        }}
        className={codeStyle({ size, variant })}
        {...props}
      >
        {children}
      </code>
    );
  }
);

Code.displayName = "Code";
