// components/solid/src/core/modal.tsx
"use client";
import { Dialog as DialogPrimitives } from "@ark-ui/solid";
import { IconX } from "@tabler/icons-solidjs";
import {JSX, splitProps} from "solid-js"
import { cva, VariantProps } from "class-variance-authority";
import { ButtonProps } from "./button";
import { IconButton } from "./icon-button";

const Modal = DialogPrimitives.Root;

const ModalTrigger = DialogPrimitives.Trigger;

const ModalHeader = (props: JSX.HTMLAttributes<HTMLDivElement>) => (
  <div
    class="text-base-900 flex h-12 min-h-12 items-center gap-x-3 px-2 text-center"
    {...props}
  />
);


const ModalTitle = (props: DialogPrimitives.TitleProps) => (
  <DialogPrimitives.Title
    class="flex-1 text-start text-lg font-semibold"
    {...props}
  />
);


const ModalBody = (props: JSX.HTMLAttributes<HTMLDivElement>) => (
  <div
    class="text-base-600 w-full flex-1 overflow-auto px-2"
    {...props}
  />
);

ModalBody.displayName = "ModalBody";

const modalContentStyle = cva(
  "duration-400 bg-base-0 flex w-full flex-col shadow-md transition-all data-[state=open]:visible data-[state=closed]:invisible data-[state=closed]:translate-y-4 data-[state=open]:translate-y-0 data-[state=closed]:opacity-0 data-[state=open]:opacity-100",
  {
    variants: {
      size: {
        xs: "max-h-[70vh] max-w-xs sm:rounded",
        sm: "max-h-[70vh] max-w-sm sm:rounded",
        md: "max-h-[70vh] max-w-md sm:rounded",
        lg: "max-h-[70vh] max-w-lg sm:rounded",
        xl: "max-h-[70vh] max-w-xl sm:rounded",
        "2xl": "max-h-[70vh] max-w-2xl sm:rounded",
        "3xl": "max-h-[70vh] max-w-3xl sm:rounded",
        fullscreen: "h-screen w-screen rounded-none",
      },
    },
    defaultVariants: {
      size: "md",
    },
  },
);

interface ModalContentProps extends DialogPrimitives.ContentProps, VariantProps<typeof modalContentStyle> {}

const ModalContent = (props: ModalContentProps) =>{
    const [local, rest] = splitProps(props, ['size'])


    return (
        <>
    <DialogPrimitives.Backdrop class="duration-400 pointer-events-none fixed inset-0 z-50 block bg-neutral-800 bg-opacity-0 backdrop-blur-sm backdrop-brightness-50 transition-all data-[state=open]:visible data-[state=closed]:invisible data-[state=open]:bg-opacity-50" />
    <DialogPrimitives.Positioner class="fixed left-0 top-0 z-50 flex h-screen w-screen items-center justify-center">
      <DialogPrimitives.Content
        
        class={modalContentStyle({ size: local.size, class: rest.class })}
        {...props}
        />
    </DialogPrimitives.Positioner>
  </>)
    } 


const ModalFooter = (props: JSX.HTMLAttributes<HTMLDivElement>) => (
  <div class="text-base-600 px-4 py-2.5" {...props} />
);


const ModalCloseButton = (props: DialogPrimitives.CloseTriggerProps) => {
    const [local, rest] = splitProps(props, ['children'])
    return (
        <DialogPrimitives.CloseTrigger>
          <IconButton variant="plain" colorScheme="black" size="sm" {...rest}>
            {local.children ?? <IconX class="h-5 w-5" />}
          </IconButton>
        </DialogPrimitives.CloseTrigger>
      )
}
;

ModalCloseButton.displayName = "ModalCloseButton";

export {
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent,
  ModalFooter,
  ModalHeader,
  ModalTitle,
  ModalTrigger,
};

// apps/web/src/react/components/core/modal.tsx
"use client";
import React, { InputHTMLAttributes } from "react";
import { Dialog as DialogPrimitives, Portal } from "@ark-ui/react";
import { ButtonProps } from "./button";
import { cva, VariantProps } from "class-variance-authority";
import { IconButton } from "./icon-button";
import { IconX } from "@tabler/icons-react";

export const Modal = DialogPrimitives.Root;

export const ModalTrigger = DialogPrimitives.Trigger;

export const ModalHeader = ({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) => (
  <div
    className="flex h-12 min-h-12 items-center gap-x-3 px-2 text-center"
    {...props}
  />
);

ModalHeader.displayName = "ModalHeader";

export const ModalTitle = React.forwardRef<
  React.ElementRef<typeof DialogPrimitives.Title>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitives.Title>
>(({ className, ...props }, ref) => (
  <DialogPrimitives.Title
    ref={ref}
    className="flex-1 text-start text-lg font-semibold"
    {...props}
  />
));

ModalTitle.displayName = "ModalTitle";

export const ModalBody = React.forwardRef<
  HTMLDivElement,
  InputHTMLAttributes<HTMLInputElement>
>(({ className, children, ...props }, ref) => (
  <div ref={ref} className="flex-1 overflow-auto px-4" {...props}>
    {children}
  </div>
));

ModalBody.displayName = "ModalBody";

const modalContentStyle = cva(
  "duration-400 fixed z-50 flex max-h-screen w-full flex-col border bg-white shadow-md transition-all data-[state=closed]:invisible data-[state=closed]:opacity-0 data-[state=open]:opacity-100",
  {
    variants: {
      size: {
        xs: "left-1/2 top-[50%] max-h-[70vh] max-w-xs -translate-x-1/2 -translate-y-[60%] sm:rounded-md",
        sm: "left-1/2 top-[50%] max-h-[70vh] max-w-sm -translate-x-1/2 -translate-y-[60%] sm:rounded-md",
        md: "left-1/2 top-[50%] max-h-[70vh] max-w-md -translate-x-1/2 -translate-y-[60%] sm:rounded-md",
        lg: "left-1/2 top-[50%] max-h-[70vh] max-w-lg -translate-x-1/2 -translate-y-[60%] sm:rounded-md",
        xl: "left-1/2 top-[50%] max-h-[70vh] max-w-xl -translate-x-1/2 -translate-y-[60%] sm:rounded-md",
        fullscreen: "inset-0 h-screen w-screen rounded-none",
      },
    },
    defaultVariants: {
      size: "md",
    },
  }
);

interface ModalContentProps extends VariantProps<typeof modalContentStyle> {}

export const ModalContent = React.forwardRef<
  React.ElementRef<typeof DialogPrimitives.Content> & ModalContentProps,
  React.ComponentPropsWithoutRef<typeof DialogPrimitives.Content> &
    ModalContentProps
>(({ className, size, ...props }, ref) => (
  <Portal>
    <DialogPrimitives.Backdrop className="pointer-events-none fixed inset-0 z-50 block bg-neutral-900 bg-opacity-0 transition-all duration-500 data-[state=open]:visible data-[state=closed]:invisible data-[state=open]:bg-opacity-50" />
    <DialogPrimitives.Positioner>
      <DialogPrimitives.Content
        ref={ref}
        className={modalContentStyle({ size })}
        {...props}
      />
    </DialogPrimitives.Positioner>
  </Portal>
));

ModalContent.displayName = "ModalContent";

export const ModalFooter = ({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) => (
  <div className="px-4 py-2.5" {...props} />
);

ModalFooter.displayName = "ModalFooter";

export const ModalCloseButton = React.forwardRef<
  HTMLButtonElement,
  ButtonProps
>(({ children, ...props }, ref) => (
  <DialogPrimitives.CloseTrigger ref={ref} asChild>
    <IconButton variant="plain" colorScheme="black" size="sm" {...props}>
      {children || <IconX className="h-5 w-5" />}
    </IconButton>
  </DialogPrimitives.CloseTrigger>
));

ModalCloseButton.displayName = "ModalCloseButton";
