// apps/web/src/react/components/core/alert-dialog.tsx
"use client";

import * as React from "react";
import { Dialog as DialogPrimitives, Portal } from "@ark-ui/react";
import { Button } from "./button";

const AlertDialog = DialogPrimitives.Root;

const AlertDialogTrigger = DialogPrimitives.Trigger;

const AlertDialogContent = React.forwardRef<
  React.ElementRef<typeof DialogPrimitives.Content>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitives.Content>
>(({ className, ...props }, ref) => (
  <Portal>
    <DialogPrimitives.Backdrop className="pointer-events-none fixed inset-0 z-50 block bg-neutral-900 bg-opacity-0 transition-all duration-400 data-[state=open]:visible data-[state=closed]:invisible data-[state=open]:bg-opacity-50" />

    <DialogPrimitives.Positioner>
      <DialogPrimitives.Content
        ref={ref}
        className={
          "bg-white w-96 fixed left-[50%] top-[50%] z-50 grid max-w-lg translate-x-[-50%] data-[state=open]:translate-y-[-80%] data-[state=closed]:translate-y-[-70%] gap-4 border bg-background p-6 shadow-lg transition-all duration-200 data-[state=open]:visible data-[state=closed]:invisible data-[state=open]:opacity-100 data-[state=closed]:opacity-0 rounded " +
          className
        }
        {...props}
      />
    </DialogPrimitives.Positioner>
  </Portal>
));
AlertDialogContent.displayName = DialogPrimitives.Content.displayName;

const AlertDialogHeader = ({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) => (
  <div
    className={"flex flex-col space-y-2 text-center sm:text-left " + className}
    {...props}
  />
);
AlertDialogHeader.displayName = "AlertDialogHeader";

const AlertDialogFooter = ({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) => (
  <div
    className={"flex flex-col gap-y-2 items-stretch" + className}
    {...props}
  />
);
AlertDialogFooter.displayName = "AlertDialogFooter";

const AlertDialogTitle = React.forwardRef<
  React.ElementRef<typeof DialogPrimitives.Title>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitives.Title>
>(({ className, ...props }, ref) => (
  <DialogPrimitives.Title
    ref={ref}
    className={"text-lg font-semibold " + className}
    {...props}
  />
));
AlertDialogTitle.displayName = DialogPrimitives.Title.displayName;

const AlertDialogDescription = React.forwardRef<
  React.ElementRef<typeof DialogPrimitives.Description>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitives.Description>
>(({ className, ...props }, ref) => (
  <DialogPrimitives.Description
    ref={ref}
    className={"text-sm text-muted-foreground " + className}
    {...props}
  />
));
AlertDialogDescription.displayName = DialogPrimitives.Description.displayName;

// const AlertDialogAction = React.forwardRef<
//   React.ElementRef<typeof DialogPrimitives.Action>,
//   React.ComponentPropsWithoutRef<typeof DialogPrimitives.Action>
// >(({ className, ...props }, ref) => (
//   <DialogPrimitives.Action
//     ref={ref}
//     className={buttonStyle({ className })}
//     {...props}
//   />
// ));
// AlertDialogAction.displayName = DialogPrimitives.Action.displayName;

const AlertDialogCancel = React.forwardRef<
  React.ElementRef<typeof DialogPrimitives.CloseTrigger>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitives.CloseTrigger>
>(({ className, children, ...props }, ref) => (
  <DialogPrimitives.CloseTrigger asChild ref={ref} {...props}>
    <Button variant="outline">{children}</Button>
  </DialogPrimitives.CloseTrigger>
));
AlertDialogCancel.displayName = "AlertDialogCancel";

export {
  AlertDialog,
  AlertDialogTrigger,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogFooter,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogCancel,
};

// components/solid/src/core/alert-dialog.tsx
"use client";

import { Dialog as DialogPrimitives } from "@ark-ui/solid";
import { Button } from "./button";
import { splitProps, JSX } from "solid-js";

const AlertDialog = DialogPrimitives.Root;

const AlertDialogTrigger = DialogPrimitives.Trigger;

interface AlertDialogContentProps extends DialogPrimitives.ContentProps {

}

const AlertDialogContent = (props: AlertDialogContentProps) =>
    
    
    {
        const [local, rest] = splitProps(props, ['class'])
        return(
  <>
    <DialogPrimitives.Backdrop class="duration-400 pointer-events-none fixed inset-0 z-50 block bg-neutral-800 bg-opacity-0 backdrop-blur-sm backdrop-brightness-50 transition-all data-[state=open]:visible data-[state=closed]:invisible data-[state=open]:bg-opacity-50" />

    <DialogPrimitives.Positioner class="fixed left-0 top-0 z-50 flex h-screen w-screen items-center justify-center">
      <DialogPrimitives.Content
        class={
          "bg-base-0 data-[state=closed]:translate-0 grid w-96 max-w-lg gap-4 rounded p-6 shadow-lg transition-all duration-200 data-[state=open]:visible data-[state=closed]:invisible data-[state=open]:-translate-y-14 data-[state=closed]:opacity-0 data-[state=open]:opacity-100 " +
          local.class
        }
        {...rest}
      />
    </DialogPrimitives.Positioner>
  </>
)};

const AlertDialogHeader = (props: JSX.HTMLAttributes<HTMLDivElement>) => {
    const [local, rest] = splitProps(props, ['class'])
    return  (
        <div
          class={"flex flex-col space-y-2 text-center sm:text-left " + local.class}
          {...rest}
        />
      )
}

interface AlertDialogFooterProps extends JSX.HTMLAttributes<HTMLDivElement> {

}

const AlertDialogFooter = (props: AlertDialogFooterProps) => {
    const [local, rest] = splitProps(props, ['class'])
    return (
        <div
          class={"flex flex-col items-stretch gap-y-2 " + local.class}
          {...rest}
        />
      )
};

const AlertDialogTitle = (props: DialogPrimitives.TitleProps) => 
    
    {
        const [local, rest] = splitProps(props, ['class'])

         return(
  <DialogPrimitives.Title
    class={"text-base-800 text-lg font-semibold " + local.class}
    {...rest}
  />
)};



const AlertDialogDescription = (props: DialogPrimitives.DescriptionProps) => {
    const [local, rest] = splitProps(props, ['class'])

    return (
  <DialogPrimitives.Description
    class={"text-base-500 text-sm " + local.class}
    {...rest}
  />
)};



interface AlertDialogCancelProps extends DialogPrimitives.CloseTriggerProps {

}

const AlertDialogCancel = (props: AlertDialogCancelProps) => 

    
    {
        const [local, rest] = splitProps(props, ['children'])
        return(
  <DialogPrimitives.CloseTrigger
    {...rest}
  >
    <Button variant="outline" colorScheme="black">
      {local.children}
    </Button>
  </DialogPrimitives.CloseTrigger>
)};

export {
  AlertDialog,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
};
