// apps/web/src/react/components/core/carousel.tsx
"use client";
import React, { forwardRef } from "react";
import {
  Carousel as CarouselPrimitives,
  useCarouselContext,
} from "@ark-ui/react";
import { cva } from "class-variance-authority";
import { IconChevronLeft, IconChevronRight } from "@tabler/icons-react";

const Carousel = forwardRef<
  React.ElementRef<typeof CarouselPrimitives.Root>,
  React.ComponentPropsWithoutRef<typeof CarouselPrimitives.Root>
>((props, ref) => {
  return (
    <CarouselPrimitives.Root
      ref={ref}
      className="relative h-full w-full max-w-full overflow-hidden bg-neutral-200"
      {...props}
    ></CarouselPrimitives.Root>
  );
});

Carousel.displayName = "Carousel";

const carouselTriggerStyle = cva(
  "absolute top-1/2 z-40 bg-white flex aspect-square -translate-y-1/2 transform cursor-pointer items-center justify-center rounded-full text-neutral-500 shadow transition-colors hover:bg-neutral-100",
  {
    variants: {
      position: {
        left: "left-4",
        right: "right-4",
      },
      size: {
        xs: "w-8",
        sm: "w-9",
        md: "w-10",
        ld: "w-11",
        xl: "w-12",
      },
    },
    defaultVariants: {
      position: "left",
      size: "md",
    },
  }
);

const CarouselControl = forwardRef<
  React.ElementRef<typeof CarouselPrimitives.NextTrigger>,
  React.ComponentPropsWithoutRef<typeof CarouselPrimitives.NextTrigger>
>(() => {
  const { canScrollNext, canScrollPrev } = useCarouselContext();
  return (
    <CarouselPrimitives.Control>
      {canScrollPrev && (
        <CarouselPrimitives.PrevTrigger
          className={carouselTriggerStyle({
            position: "left",
          })}
        >
          <IconChevronLeft />
        </CarouselPrimitives.PrevTrigger>
      )}
      {canScrollNext && (
        <CarouselPrimitives.NextTrigger
          className={carouselTriggerStyle({
            position: "right",
          })}
        >
          <IconChevronRight />
        </CarouselPrimitives.NextTrigger>
      )}
    </CarouselPrimitives.Control>
  );
});

CarouselControl.displayName = "CarouselControl";

const CarouselItemGroup = forwardRef<
  React.ElementRef<typeof CarouselPrimitives.ItemGroup>,
  React.ComponentPropsWithoutRef<typeof CarouselPrimitives.ItemGroup>
>(({ children, ...props }, ref) => (
  <CarouselPrimitives.Viewport>
    <CarouselPrimitives.ItemGroup ref={ref} {...props}>
      {children}
    </CarouselPrimitives.ItemGroup>
  </CarouselPrimitives.Viewport>
));

CarouselItemGroup.displayName = "CarouselItemGroup";

const CarouselItem = forwardRef<
  React.ElementRef<typeof CarouselPrimitives.Item>,
  React.ComponentPropsWithoutRef<typeof CarouselPrimitives.Item>
>(({ children, ...props }, ref) => (
  <CarouselPrimitives.Item
    ref={ref}
    {...props}
    className="h-full w-full object-cover"
    asChild
  >
    {children}
  </CarouselPrimitives.Item>
));

CarouselItem.displayName = "CarouselItem";

interface CarouselIndicatorGroupProps {
  itemCount: number;
}

const CarouselIndicatorGroup = forwardRef<
  React.ElementRef<typeof CarouselPrimitives.IndicatorGroup> &
    CarouselIndicatorGroupProps,
  React.ComponentPropsWithoutRef<typeof CarouselPrimitives.IndicatorGroup> &
    CarouselIndicatorGroupProps
>(({ children, itemCount, ...props }, ref) => {
  return (
    <CarouselPrimitives.IndicatorGroup
      ref={ref}
      className="absolute bottom-2 left-1/2 z-50 flex h-max w-max -translate-x-1/2 transform gap-x-1 rounded-full bg-neutral-800 p-1.5"
      {...props}
    >
      {Array.from(Array(itemCount).keys()).map((_, index) => (
        <CarouselPrimitives.Indicator
          index={index}
          className="h-2 w-2 rounded-full bg-neutral-600 data-[current]:bg-neutral-200"
        />
      ))}
      {children}
    </CarouselPrimitives.IndicatorGroup>
  );
});

CarouselIndicatorGroup.displayName = "CarouselIndicatorGroup";

export {
  Carousel,
  CarouselItemGroup,
  CarouselControl,
  CarouselIndicatorGroup,
  CarouselItem,
};

// components/solid/src/core/carousel.tsx
import {
  Carousel as CarouselPrimitives,
  useCarouselContext,
} from "@ark-ui/solid";
import { IconChevronLeft, IconChevronRight } from "@tabler/icons-solidjs";
import { cva } from "class-variance-authority";
import { splitProps } from "solid-js";

const Carousel = (props: CarouselPrimitives.RootProps) => {
  return (
    <CarouselPrimitives.Root
      
      class="bg-base-200 relative h-full w-full max-w-full overflow-hidden"
      {...props}
    ></CarouselPrimitives.Root>
  );
};

Carousel.displayName = "Carousel";

const carouselTriggerStyle = cva(
  "text-base-500 hover:bg-base-100 absolute top-1/2 z-40 flex aspect-square -translate-y-1/2 transform cursor-pointer items-center justify-center rounded-full bg-white shadow transition-colors",
  {
    variants: {
      position: {
        left: "left-4",
        right: "right-4",
      },
      size: {
        xs: "w-8",
        sm: "w-9",
        md: "w-10",
        ld: "w-11",
        xl: "w-12",
      },
    },
    defaultVariants: {
      position: "left",
      size: "md",
    },
  },
);

const CarouselControl = () => {
  const carouselContext = useCarouselContext();
  const { canScrollNext, canScrollPrev } = carouselContext()
  return (
    <CarouselPrimitives.Control>
      {canScrollPrev && (
        <CarouselPrimitives.PrevTrigger
          class={carouselTriggerStyle({
            position: "left",
          })}
        >
          <IconChevronLeft />
        </CarouselPrimitives.PrevTrigger>
      )}
      {canScrollNext && (
        <CarouselPrimitives.NextTrigger
          class={carouselTriggerStyle({
            position: "right",
          })}
        >
          <IconChevronRight />
        </CarouselPrimitives.NextTrigger>
      )}
    </CarouselPrimitives.Control>
  );
};


const CarouselItemGroup = (props: CarouselPrimitives.ItemGroupProps) => {
    const [local, restProps] = splitProps(props, ['children'])
    return (
  
        <CarouselPrimitives.ItemGroup {...restProps}>
          {local.children}
        </CarouselPrimitives.ItemGroup>
      
    )
}


const CarouselItem = (props: CarouselPrimitives.ItemProps) => {
    const [local, restProps] = splitProps(props, ['children'])

    return (
        <CarouselPrimitives.Item
          {...restProps}
          class="h-full w-full object-cover"
          
        >
          {local.children}
        </CarouselPrimitives.Item>
      )
}

CarouselItem.displayName = "CarouselItem";

interface CarouselIndicatorGroupProps extends CarouselPrimitives.IndicatorGroupProps {
  itemCount: number;
}

const CarouselIndicatorGroup = (props: CarouselIndicatorGroupProps) => {
    const [local, restProps] = splitProps(props, ['children', 'itemCount'])

  return (
    <CarouselPrimitives.IndicatorGroup
      class="bg-base-800 absolute bottom-2 left-1/2 z-50 flex h-max w-max -translate-x-1/2 transform gap-x-1 rounded-full p-1.5"
      {...restProps}
    >
      {Array.from(Array(local.itemCount).keys()).map((_, index) => (
        <CarouselPrimitives.Indicator
          index={index}
          class="bg-base-600 data-[current]:bg-base-200 h-2 w-2 rounded-full"
        />
      ))}
      {local.children}
    </CarouselPrimitives.IndicatorGroup>
  );
};

CarouselIndicatorGroup.displayName = "CarouselIndicatorGroup";

export {
  Carousel,
  CarouselControl,
  CarouselIndicatorGroup,
  CarouselItem,
  CarouselItemGroup,
};
