// components/react/src/core/dropzone.tsx
"use client";
import React, { forwardRef } from "react";
import { FileUpload as FileUploadPrimitives } from "@ark-ui/react";
import { IconTrash } from "@tabler/icons-react";

const Dropzone = forwardRef<
  React.ElementRef<typeof FileUploadPrimitives.Root>,
  React.ComponentPropsWithoutRef<typeof FileUploadPrimitives.Root>
>(({ children, ...props }, ref) => {
  return (
    <FileUploadPrimitives.Root
      ref={ref}
      className="relative aspect-video w-full"
      {...props}
    >
      <FileUploadPrimitives.Dropzone className="mb-4 flex h-full w-full flex-col items-center justify-center gap-y-4 rounded-sm border border-base-300 pb-5">
        {children}
      </FileUploadPrimitives.Dropzone>
      <FileUploadPrimitives.HiddenInput className="" />

      <FileUploadPrimitives.ItemGroup className="relative space-y-2">
        <FileUploadPrimitives.Context>
          {({ acceptedFiles }) =>
            acceptedFiles.map((file, index) => (
              <FileUploadPrimitives.Item
                key={index}
                file={file}
                className="flex items-center gap-x-4 rounded-sm border border-base-300 p-4"
              >
                {file.type.startsWith("image") ? (
                  <FileUploadPrimitives.ItemPreview type="image/*" className="">
                    <FileUploadPrimitives.ItemPreviewImage
                      src={URL.createObjectURL(file)}
                      className="h-12 w-12 object-contain object-center"
                    />
                  </FileUploadPrimitives.ItemPreview>
                ) : (
                  <FileUploadPrimitives.ItemPreview
                    type=".*"
                    className="flex h-12 w-12 items-center justify-center rounded border border-base-300 bg-base-200 text-sm font-semibold uppercase text-base-500"
                  >
                    {file.name.split(".").pop()}
                  </FileUploadPrimitives.ItemPreview>
                )}

                <div className="flex flex-1 flex-col">
                  <FileUploadPrimitives.ItemName className="text-sm font-medium text-base-800" />
                  <FileUploadPrimitives.ItemSizeText className="text-sm text-base-500" />
                </div>
                <FileUploadPrimitives.ItemDeleteTrigger className="rounded border border-base-300 p-1.5 transition-colors hover:bg-base-200">
                  <IconTrash className="h-4 w-4 text-base-600" />
                </FileUploadPrimitives.ItemDeleteTrigger>
              </FileUploadPrimitives.Item>
            ))
          }
        </FileUploadPrimitives.Context>
      </FileUploadPrimitives.ItemGroup>
    </FileUploadPrimitives.Root>
  );
});

Dropzone.displayName = "Dropzone";

const DropzoneText = forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ children, ...props }, ref) => {
  return (
    <div ref={ref} className="text-lg text-base-600" {...props}>
      {children}
    </div>
  );
});

DropzoneText.displayName = "DropzoneText";

const DropzoneTrigger = FileUploadPrimitives.Trigger;

export { Dropzone, DropzoneTrigger, DropzoneText };

// components/solid/src/core/dropzone.tsx
import { FileUpload as FileUploadPrimitives } from "@ark-ui/solid";
import { IconTrash } from "@tabler/icons-solidjs";
import {For, JSX, splitProps} from "solid-js"

const DropzoneTrigger = FileUploadPrimitives.Trigger;


const Dropzone = (props: FileUploadPrimitives.RootProps) => {
    const [local, rest] = splitProps(props, ["children"])
    
  return (
    <FileUploadPrimitives.Root
      class="relative aspect-video w-full"
      {...rest}
    >
      <FileUploadPrimitives.Dropzone class="border-base-300 mb-4 flex h-full w-full flex-col items-center justify-center gap-y-4 rounded-sm border pb-5">
        {local.children}
      </FileUploadPrimitives.Dropzone>
      <FileUploadPrimitives.HiddenInput class="" />

      <FileUploadPrimitives.ItemGroup class="relative space-y-2">
        <FileUploadPrimitives.Context>
          {(context) =>

<For each={context().acceptedFiles}>
{(file) => (

<FileUploadPrimitives.Item
file={file}
class="border-base-300 flex items-center gap-x-4 rounded-sm border p-4"
>
{file.type.startsWith("image") ? (
  <FileUploadPrimitives.ItemPreview type="image/*" class="">
    <FileUploadPrimitives.ItemPreviewImage
      src={URL.createObjectURL(file)}
      class="h-12 w-12 object-contain object-center"
    />
  </FileUploadPrimitives.ItemPreview>
) : (
  <FileUploadPrimitives.ItemPreview
    type=".*"
    class="border-base-300 bg-base-200 text-base-500 flex h-12 w-12 items-center justify-center rounded border text-sm font-semibold uppercase"
  >
    {file.name.split(".").pop()}
  </FileUploadPrimitives.ItemPreview>
)}

<div class="flex flex-1 flex-col">
  <FileUploadPrimitives.ItemName class="text-base-800 text-sm font-medium" />
  <FileUploadPrimitives.ItemSizeText class="text-base-500 text-sm" />
</div>
<FileUploadPrimitives.ItemDeleteTrigger class="border-base-300 hover:bg-base-200 rounded border p-1.5 transition-colors">
  <IconTrash class="text-base-600 h-4 w-4" />
</FileUploadPrimitives.ItemDeleteTrigger>
</FileUploadPrimitives.Item>
)}
</For>

          }
        </FileUploadPrimitives.Context>
      </FileUploadPrimitives.ItemGroup>
    </FileUploadPrimitives.Root>
  );
};


const DropzoneText = (props : JSX.HTMLAttributes<HTMLDivElement>
) => {
    const [local, rest] = splitProps(props, ["children"])

  return (
    <div class="text-base-600 text-lg" {...rest}>
      {local.children}
    </div>
  );
}



export { Dropzone, DropzoneText, DropzoneTrigger };
