// apps/web/src/react/components/core/label.tsx
import { DetailedHTMLProps, forwardRef } from "react";

const Label = forwardRef<
  HTMLLabelElement,
  DetailedHTMLProps<React.LabelHTMLAttributes<HTMLElement>, HTMLLabelElement>
>(({ className, ...props }, ref) => (
  <label
    ref={ref}
    className={
      "mb-1 text-sm font-medium data-[invalid]:text-red-500 " + className
    }
    {...props}
  />
));

Label.displayName = "Label";

export { Label };

// components/solid/src/core/label.tsx
import { JSX, splitProps } from "solid-js";

interface LabelProps extends JSX.LabelHTMLAttributes<HTMLLabelElement> {

};

 const Label = (props: LabelProps) => {
  const [local, labelProps] = splitProps(props, ["class"]);
  return (
    <label
      class={`text-base-900 mb-1 text-sm font-medium data-[invalid]:text-red-500 ${local.class || ""}`}
      {...labelProps}
    />
  );
};
export {Label}
