// components/react/src/core/qr-code.tsx
import { QrCode as QrCodePrimitives } from "@ark-ui/react";
import React, { forwardRef } from "react";

const QrCode = forwardRef<
  React.ElementRef<typeof QrCodePrimitives.Root>,
  React.ComponentPropsWithoutRef<typeof QrCodePrimitives.Root>
>(({ children, ...props }, ref) => {
  return (
    <QrCodePrimitives.Root ref={ref} className="fill-base-900" {...props}>
      <QrCodePrimitives.Frame>
        <QrCodePrimitives.Pattern />
      </QrCodePrimitives.Frame>
      {children}
    </QrCodePrimitives.Root>
  );
});

QrCode.displayName = "QrCode";

const QrCodeOverlay = forwardRef<
  React.ElementRef<typeof QrCodePrimitives.Overlay>,
  React.ComponentPropsWithoutRef<typeof QrCodePrimitives.Overlay>
>((props, ref) => {
  return (
    <QrCodePrimitives.Overlay
      ref={ref}
      {...props}
      className="w-10 rounded-full border-4 border-white"
    />
  );
});

QrCodeOverlay.displayName = "QrCodeOverlay";

export { QrCode, QrCodeOverlay };

// components/solid/src/core/qr-code.tsx
import { QrCode as QrCodePrimitives } from "@ark-ui/solid";
import { splitProps } from "solid-js";

const QrCode =(props:QrCodePrimitives.RootProps) => {

    const [local, rest] = splitProps(props, ['children'])
  return (
    <QrCodePrimitives.Root class="fill-base-900" {...rest}>
      <QrCodePrimitives.Frame>
        <QrCodePrimitives.Pattern />
      </QrCodePrimitives.Frame>
      {local.children}
    </QrCodePrimitives.Root>
  );
};

QrCode.displayName = "QrCode";

const QrCodeOverlay = (props: QrCodePrimitives.OverlayProps) => {
  return (
    <QrCodePrimitives.Overlay
      {...props}
      class="w-10 rounded-full border-4 border-white"
    />
  );
};


export { QrCode, QrCodeOverlay };
