// apps/web/src/react/components/core/table.tsx
import { forwardRef } from "react";

const Table = forwardRef<
  HTMLTableElement,
  React.HTMLAttributes<HTMLTableElement>
>(({ className, ...props }, ref) => (
  <div className="relative w-full overflow-auto">
    <table ref={ref} className={"w-full caption-bottom text-sm"} {...props} />
  </div>
));
Table.displayName = "Table";

const TableHeader = forwardRef<
  HTMLTableSectionElement,
  React.HTMLAttributes<HTMLTableSectionElement>
>(({ className, ...props }, ref) => (
  <thead ref={ref} className={"[&_tr]:border-b"} {...props} />
));
TableHeader.displayName = "TableHeader";

const TableBody = forwardRef<
  HTMLTableSectionElement,
  React.HTMLAttributes<HTMLTableSectionElement>
>(({ className, ...props }, ref) => (
  <tbody ref={ref} className={"[&_tr:last-child]:border-0"} {...props} />
));
TableBody.displayName = "TableBody";

const TableFooter = forwardRef<
  HTMLTableSectionElement,
  React.HTMLAttributes<HTMLTableSectionElement>
>(({ className, ...props }, ref) => (
  <tfoot
    ref={ref}
    className={
      "border-t bg-neutral-200 pointer-events-none font-medium [&>tr]:last:border-b-0"
    }
    {...props}
  />
));
TableFooter.displayName = "TableFooter";

const TableRow = forwardRef<
  HTMLTableRowElement,
  React.HTMLAttributes<HTMLTableRowElement>
>(({ className, ...props }, ref) => (
  <tr
    ref={ref}
    className={
      "border-b transition-colors hover:bg-neutral-100 data-[state=selected]:bg-neutral-100"
    }
    {...props}
  />
));
TableRow.displayName = "TableRow";

const TableHead = forwardRef<
  HTMLTableCellElement,
  React.ThHTMLAttributes<HTMLTableCellElement>
>(({ className, ...props }, ref) => (
  <th
    ref={ref}
    className={
      "h-12 px-4 text-left align-middle font-medium text-neutral-700 [&:has([role=checkbox])]:pr-0"
    }
    {...props}
  />
));
TableHead.displayName = "TableHead";

const TableCell = forwardRef<
  HTMLTableCellElement,
  React.TdHTMLAttributes<HTMLTableCellElement>
>(({ className, ...props }, ref) => (
  <td
    ref={ref}
    className={"px-4 py-3 align-middle [&:has([role=checkbox])]:pr-0"}
    {...props}
  />
));
TableCell.displayName = "TableCell";

const TableCaption = forwardRef<
  HTMLTableCaptionElement,
  React.HTMLAttributes<HTMLTableCaptionElement>
>(({ className, ...props }, ref) => (
  <caption
    ref={ref}
    className={"mt-4 text-sm text-muted-foreground"}
    {...props}
  />
));
TableCaption.displayName = "TableCaption";

export {
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableHead,
  TableRow,
  TableCell,
  TableCaption,
};

// components/solid/src/core/table.tsx
import {JSX} from "solid-js"

interface TableProps extends JSX.HTMLAttributes<HTMLTableElement> {
}
const Table = (props: TableProps) => (
  <div class="relative w-full overflow-auto">
    <table  class={"w-full caption-bottom text-sm"} {...props} />
  </div>
);

// 
// 
// 
// 
// 

interface TableHeaderProps extends JSX.HTMLAttributes<HTMLTableSectionElement> {
}

const TableHeader = (props: TableHeaderProps) => (
  <thead class={"[&_tr]:border-b"} {...props} />
)

// 
// 
// 
// 
// 
interface TableBodyProps extends JSX.HTMLAttributes<HTMLTableSectionElement> {
}
const TableBody = (props:TableBodyProps) => (
  <tbody class={"[&_tr:last-child]:border-0"} {...props} />
)

// 
// 
// 
// 
// 
interface TableFooterProps extends JSX.HTMLAttributes<HTMLTableSectionElement> {
}
const TableFooter = (props: TableFooterProps) => (
  <tfoot
    class="bg-base-200 pointer-events-none border-t font-medium [&>tr]:last:border-b-0"
    {...props}
  />
);

// 
// 
// 
// 
// 
interface TableRowProps extends JSX.HTMLAttributes<HTMLTableRowElement> {
}

const TableRow = (props: TableRowProps) => (
  <tr
    class={
      "text-base-600 hover:bg-base-100 data-[state=selected]:bg-base-100 border-b transition-colors"
    }
    {...props}
  />
);

// 
// 
// 
// 
// 

interface TableHeadProps extends JSX.ThHTMLAttributes<HTMLTableCellElement> {
}

const TableHead = (props: TableHeadProps) => (
  <th
    class={
      "text-base-700 h-12 px-4 text-left align-middle font-medium [&:has([role=checkbox])]:pr-0"
    }
    {...props}
  />
);

// 
// 
// 
// 
// 

interface TableCellProps extends JSX.TdHTMLAttributes<HTMLTableCellElement> {
}

const TableCell = (props: TableCellProps) => (
  <td
    class={"px-4 py-3 align-middle [&:has([role=checkbox])]:pr-0"}
    {...props}
  />
);

// 
// 
// 
// 
// 

interface TableCaptionProps extends JSX.HTMLAttributes<HTMLElement> {
}
const TableCaption =(props:TableCaptionProps) => (
  <caption
    
    class={"text-muted-foreground mt-4 text-sm"}
    {...props}
  />
)

// 
// 
// 
// 
// 

export {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
};
